export default {
  batchUpdateDeviceInfoMng: '/batchUpdateDeviceInfo',
  downloadErrorDeviceMng: '/downloadErrorDevice',
  getDeviceList: '/selectDevicePage', // 设备列表
  getDeviceSelectors: '/infoList',
  getDmpList: '/device_manage/getGroupTreeList',
  getDmpUserList: '/device_manage/getGroupAccountsList',
  deleteDMPGroup: '/deleteDMPGroup',
  getDetails: '/devDetails', // 设备详情
  addDevice: '/devDropList',
  deleteSingleDevice: '/removeSingleDevice',
  deleteMultiDevice: '/removeMultiDevice',
  submitDeviceInfo: '/addDevice',
  // getPosition: '/getPosition',
  // getLog: '/logDetails',
  getAddGronp: '/device_manage/getParentGroupList',
  submitGronp: '/device_manage/addGroup',
  getAddUser: '/device/getDeviceTypeList',
  getModifyUser: '/getModifyUser',
  getProvinceList: '/area/getProvinceList',
  getCityList: '/area/getCityList',
  getCountryList: '/area/getCountyList',
  submitUser: '/device_manage/addDmpAccount',
  getDmpMakerAll: '/device_manage/getDmpMakerAll',
  getSubscribeList: '/sub/list',
  getDeviceTypeAndMakerAndModel: '/device/getDeviceTypeAndDMPMakerAnddMPModel',
  getDmpAllUser: '/device_manage/getGroupAllAccountsList',
  onOffDmpServer: '/device_manage/disabledUser',
  deleteDmpUser: '/device_manage/deleteUser',
  addSubscribe: '/sub/add',
  delSubscribe: '/sub/remove',
  getSubscribeInfo: '/getSubscribeInfo',
  modifySubscribe: '/modifySubscribe',
  batchExport: '/exportDeviceInfo',
  downloadTemplate: '/downloadExcel',
  // batchImport: '/batchImport',
  // uploadPreview: '/uploadPreview',
  uploadFile: '/importDeviceList',
  getLogList: '/dvcinfo', // 设备日志列表
  getAccountList: '/user/getList',
  getSubmitAccount: '/user/create',
  logsExport: '/excel/dvclog',
  deleteUser: '/user/delete',
  disableOrStart: '/user/changeStatus',
  allProject: '/project/projectTree',
  updateAccount: '/user/update',
  getRoleList: '/user/getRoleList',
  getStreetList: '/area/getStreetList',
  submitEditDevice: '/updateDeviceInfo',
};
